sonar.projectKey=mary010-sky_web-vulnerabilidad
sonar.organization=mary010-sky
sonar.projectName=Web Vulnerability Scanner
sonar.projectVersion=1.0

# Rutas del código fuente
sonar.sources=web-vulnerabilidad/backend/app,web-vulnerabilidad/frontend
sonar.tests=web-vulnerabilidad/backend/tests

# Exclusiones
sonar.exclusions=**/node_modules/**,**/venv_win/**,**/__pycache__/**,**/migrations/**,**/alembic/**,**/*.pyc

# Cobertura de Python (generada por pytest-cov)
sonar.python.coverage.reportPaths=web-vulnerabilidad/backend/coverage.xml

# Encoding
sonar.sourceEncoding=UTF-8

# Python version
sonar.python.version=3.11
